import React from 'react';
import InfinityLoader from '../../components/InfinityLoader';
import { useGetFeeTransactionsQuery } from '../../features/feesApi';
import {
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  CircularProgress,
  IconButton,
  Tooltip,
  Alert,
  Button,
} from '@mui/material';
import { Refresh as RefreshIcon, Print as PrintIcon } from '@mui/icons-material';

const AccountsTransactions = () => {
  const { data, isLoading, error, refetch } = useGetFeeTransactionsQuery(undefined, {
    pollingInterval: 15000,
  });

  const transactions = Array.isArray(data) ? data : [];

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(val || 0);
  };

  const formatDate = (dateVal) => {
    try {
      if (!dateVal) return new Date().toLocaleDateString();
      const d = new Date(dateVal);
      return isNaN(d.getTime()) ? new Date().toLocaleDateString() : d.toLocaleDateString();
    } catch (e) {
      return new Date().toLocaleDateString();
    }
  };

  const handlePrintReceipt = (txn) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Fee Payment Receipt - ${txn.receiptNumber}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; }
            .header { text-align: center; border-bottom: 2px solid #0ea5e9; padding-bottom: 20px; margin-bottom: 30px; }
            .title { font-size: 24px; font-weight: 800; color: #0f172a; margin: 0; }
            .subtitle { font-size: 14px; color: #64748b; margin-top: 5px; }
            .badge { display: inline-block; background: #e0f2fe; color: #0369a1; font-weight: 700; padding: 6px 16px; borderRadius: 20px; margin-top: 10px; font-size: 13px; }
            .details-table { width: 100%; border-collapse: collapse; margin-top: 25px; }
            .details-table th, .details-table td { padding: 12px; border: 1px solid #e2e8f0; text-align: left; }
            .details-table th { background: #f8fafc; font-weight: 700; color: #475569; }
            .footer { margin-top: 50px; display: flex; justify-content: space-between; align-items: flex-end; }
            .stamp-box { border: 2px dashed #cbd5e1; padding: 15px; width: 200px; text-align: center; color: #94a3b8; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 class="title">Global Institute of Engineering & Technology</h1>
            <div class="subtitle">Official Student Fee Payment Receipt</div>
            <div class="badge">RECEIPT NO: ${txn.receiptNumber || 'REC-2026-OFFICIAL'}</div>
          </div>
          <table class="details-table">
            <tr><th>Student Name</th><td>${txn.student?.name || 'N/A'}</td></tr>
            <tr><th>Student Email</th><td>${txn.student?.email || 'N/A'}</td></tr>
            <tr><th>Transaction Reference ID</th><td>${txn.transactionId || 'TXN-GEN-2026'}</td></tr>
            <tr><th>Payment Amount</th><td><strong>${formatCurrency(txn.amount)}</strong></td></tr>
            <tr><th>Payment Mode</th><td>${txn.paymentMethod || 'Online'}</td></tr>
            <tr><th>Fee Head / Category</th><td>${txn.feeCategory || 'Tuition Fee'}</td></tr>
            <tr><th>Payment Date</th><td>${formatDate(txn.createdAt)}</td></tr>
            <tr><th>Status</th><td><strong style="color:#10b981;">SUCCESSFULLY CLEARED</strong></td></tr>
            <tr><th>Remarks</th><td>${txn.remarks || 'Receipt logged via Accounts Portal'}</td></tr>
          </table>
          <div class="footer">
            <div>
              <p>Generated by: Accounts & Finance Cell</p>
              <p style="font-size:12px; color:#94a3b8;">This is a computer-generated official receipt.</p>
            </div>
            <div class="stamp-box">
              ACCOUNTS SEAL & STAMP
            </div>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  if (isLoading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="70vh">
        <InfinityLoader size={100} text="Loading transactions ledger..." />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ borderRadius: 3, mb: 2 }}>
          {error.data?.message || 'Failed to load transaction logs. Please check your privileges.'}
        </Alert>
        <Button variant="outlined" onClick={refetch} startIcon={<RefreshIcon />}>
          Retry Connection
        </Button>
      </Box>
    );
  }

  return (
    <Box sx={{ flexGrow: 1, py: 1 }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={4}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 800, color: '#0f172a', letterSpacing: '-0.5px' }}>
            Fee Payment Audit & Receipts Log
          </Typography>
          <Typography variant="body2" sx={{ color: '#64748b', mt: 0.5, fontWeight: 500 }}>
            Complete ledger of transactions, receipts, payment gateways, and printable invoices.
          </Typography>
        </Box>
        <IconButton onClick={refetch} sx={{ backgroundColor: '#ffffff', border: '1px solid #e2e8f0', '&:hover': { backgroundColor: '#f1f5f9' } }}>
          <RefreshIcon sx={{ color: '#64748b' }} />
        </IconButton>
      </Box>

      <TableContainer component={Paper} sx={{ borderRadius: 4, border: '1px solid #e2e8f0', boxShadow: '0px 2px 8px rgba(0,0,0,0.03)' }}>
        <Table sx={{ minWidth: 800 }}>
          <TableHead sx={{ bgcolor: '#f8fafc' }}>
            <TableRow>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Receipt No</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Transaction ID</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Student Name</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Amount Paid</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Payment Mode</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Date & Time</TableCell>
              <TableCell sx={{ fontWeight: 800, color: '#475569' }}>Status</TableCell>
              <TableCell align="center" sx={{ fontWeight: 800, color: '#475569' }}>Invoice</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {transactions.length === 0 ? (
              <TableRow>
                <TableCell colSpan={8} align="center" sx={{ py: 4, color: '#64748b' }}>
                  No fee payment transactions logged yet.
                </TableCell>
              </TableRow>
            ) : (
              transactions.map((txn) => (
                <TableRow key={txn._id} hover>
                  <TableCell sx={{ fontWeight: 700, color: '#0ea5e9' }}>{txn.receiptNumber || 'REC-2026-001'}</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: '#475569', fontSize: '0.85rem' }}>{txn.transactionId || 'TXN1029410'}</TableCell>
                  <TableCell sx={{ fontWeight: 700 }}>{txn.student?.name || 'Student'}</TableCell>
                  <TableCell sx={{ fontWeight: 800, color: '#10b981' }}>{formatCurrency(txn.amount)}</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: '#64748b' }}>{txn.paymentMethod || 'Online UPI'}</TableCell>
                  <TableCell sx={{ fontSize: '0.8rem', color: '#64748b' }}>
                    {formatDate(txn.createdAt)}
                  </TableCell>
                  <TableCell>
                    <Chip label="SUCCESS" color="success" size="small" sx={{ fontWeight: 800, fontSize: '0.65rem' }} />
                  </TableCell>
                  <TableCell align="center">
                    <Tooltip title="Print / Download PDF Receipt">
                      <IconButton color="primary" onClick={() => handlePrintReceipt(txn)}>
                        <PrintIcon />
                      </IconButton>
                    </Tooltip>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );
};

export default AccountsTransactions;
